### ISSUE TITLE
p status does not work on ubuntu

### ISSUE THREAD

**Issue by argestes** [chrismdp/p#1]
$ p
    date: invalid option -- 'j'
    Try 'date --help' for more information.

Running p after starting a pomodoro gives this error

**Comment by chrismdp** [comment]
Yep, this is a known issue (see the Limitations section of the [README](https://github.com/chrismdp/p/blob/master/README.md)).

I'd be grateful for a patch to fix this script to work with GNU `date` as well as the Unix `date` that OS X ships with.

**Comment by niko** [comment]
The equivalent to bsd-date's `-j` flag seems to be `-d`:

```
date -d "2015-05-07 23:55:14 +0200" "+%s"
1431035714
```

I tried to fix it: https://github.com/chrismdp/p/pull/2 but I don't know if I broke it for bsd date.

**Comment by chrismdp** [comment]
@argestes @niko and I fixed it in #2: please try again

**Comment by chrismdp** [comment]
Closing as now appears to work fine.

**Comment by argestes** [comment]
Yes, thanks
