### ISSUE TITLE
No tests

### ISSUE THREAD

**Issue by chrismdp** [chrismdp/p#3]
There are no tests yet, and this is a problem for future improvements to ensure we don't break existing functionality.

I'd prefer to have a no-library approach to minimise dependencies as much as possible, something like this approach:

```bash
p start > $output 2>&1
diff $output - <<!
Pomodoro started
!

[ $? -ne 0 ] && fail
```

**Comment by gerhard** [comment]
These type of tests are helpful for a rewrite, but they feel like end-to-end tests: the more you have, the worse off the codebase is.

I was thinking about teasing apart the main components using TDD, then just replacing the original code with the new components, one-by-one. Let me start with a PR that puts this in code.

**Comment by chrismdp** [comment]
As discussed in #4, I think I only want some very basic integration tests here, as I'm not planning on adding any significant functionality to the tool at all and it works as described.

You're right in that the more integration tests you have the more maintenance overhead you have, but I'm after about five that check basic functionality only.

**Comment by chrismdp** [comment]
I've added the sort of tests I'm after now: hopefully that makes my thinking clearer. Like I said, I feel the script is simple enough to only require a simple user journey implemented as one integration test.

**Comment by gerhard** [comment]
Tests looking good, fully understand where you're coming from. Looking forward to using the utility!

**Comment by chrismdp** [comment]
@gerhard thanks for the support!
