### ISSUE TITLE
Tomato character not working in Arch Linux

### ISSUE THREAD

**Issue by jerefrer** [chrismdp/p#6]
Hi there,

Thanks for p, it's awesome ... except that I can't see that beautiful tomato in my Arch VM ...

![tomato](https://cloud.githubusercontent.com/assets/140954/7605633/0015078e-f952-11e4-9565-e07148795d81.png)

I understand this may not be p's concern, but if there is a workaround maybe it would be handy to put it in the README. Right now I don't have time to search for it, but be sure I'm coming back if I do :)

**Comment by chrismdp** [comment]
Ah, such a shame! :)

Basically, you need a terminal with Emoji support. This might help?

https://bbs.archlinux.org/viewtopic.php?id=185269

**Comment by jerefrer** [comment]
Actually all I needed was to install the Symbola font: `sudo pacman -S ttf-symbola`. Worked straight after installing. Thanks for digging ;)

**Comment by chrismdp** [comment]
glad you got it working!
